name: fastapi-azure-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
              set -e

              cd ~/fastapi-azure

              git pull origin main

              if [ ! -d ".venv" ]; then
                uv venv
              fi

              ~/.local/bin/uv sync

              sudo systemctl restart fastapi
          EOF
